#!/usr/bin/python
import subprocess
import sys
import argparse
import os
parser = argparse.ArgumentParser(description ='A3 script')
parser.add_argument('credentials',help='enter ip:poat:community')
parser.add_argument('freq',type=float,help='enter frequency')
parser.add_argument('oids',nargs='+',help='enter oids')
args = parser.parse_args()
ipportcomm = args.credentials
frequency=args.freq
oid = args.oids
joinoids = " ".join(oid)
t = []
cmd = "unbuffer perl /home/anm/Desktop/assgn/A2/prober " + str(ipportcomm) +" " +str(frequency) + " -1 " + str(joinoids)
process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,shell = True)
while True:
 for out in iter(process.stdout.readline, ''):
   a = out.split("|")
   a = [int(float(k)) for k in a]
   t.append(a[0])
   del a[0] 
   for a1,b1 in zip(oid,a):
    c1 = str(t[0]).strip()+'000000000'
    #print a1,b1,c1
    cmd = "curl -i -XPOST 'http://localhost:8086/write?db=A3' -u ats:atslabb00 --data-binary 'rate,oid=%s value=%d %d' > /dev/null"%(a1,long(b1),int(c1))
    os.system(cmd)
   t=[]



